### ISSUE TITLE
Rviz. No messages received after 0.7.15-alpha.

### ISSUE THREAD

**Issue by tohax** [ElettraSciComp/witmotion_IMU_ros#10]
wt901c. Все версии до 0.7.15-alpha включительно работают. На следующих версиях Rviz говорит, что сообщения не получены.

**Comment by twdragon** [comment]
Это говорит RViz или нода? Первым делом проверьте конфигурацию сборки сообщения IMU. Возможно, в новой версии примера конфигурационного файла не совпадают какие-то параметры, и сообщение IMU не собирается. Особенно это касается `use_native_orientation`, для этого надо через приложение-контроллер включить передачу ориентации в форме кватерниона

**Comment by twdragon** [comment]
Я только что тестировал WT901 в бескорпусном исполнении, с параметром `use_native_orientation` IMU сообщение публикуется только с включенным аппаратно кватернионом.

**Comment by twdragon** [comment]
@tohax а что в логе `rostopic echo`?

**Comment by tohax** [comment]
use_native_orientation: false решило проблему. Настраивать кватернион еще не пробовал. Благодарю. Issue можно закрывать.
