### ISSUE TITLE
WT901C-485 is not working in ros2 humble

### ISSUE THREAD

**Issue by its-seon** [ElettraSciComp/witmotion_IMU_ros#34]
Hi i have a problem about WT901C-485.

**Environment:
Ubuntu 20.04
ROS2 Humble with docker
IMU WT901C-485**

When i run ros2 launch witmotion_ros wt901_launch.py, i get under the error.
root@ubuntu-950XDA:~/home/colcon_ws# ros2 launch witmotion_ros wt901_launch.py 
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-11-13-04-39-00-217161-ubuntu-950XDA-28525
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [witmotion_ros_node-1]: process started with pid [28526]
[witmotion_ros_node-1] [INFO] [1699850340.261470118] [ROSWitmotionSensorController]: Controller started
[witmotion_ros_node-1] [INFO] [1699850340.261552591] [MinimalPublisher]: QT spin !!!!!
[witmotion_ros_node-1] [ERROR] [1699850340.420747476] [ROSWitmotionSensorController]: Sensor error: Timed out waiting for data, please check device connection and baudrate!
[witmotion_ros_node-1] [INFO] [1699850340.420804741] [ROSWitmotionSensorController]: Entering SUSPENDED state
[witmotion_ros_node-1] QObject::killTimer: Timers cannot be stopped from another thread
[witmotion_ros_node-1] QObject::~QObject: Timers cannot be stopped from another thread
[witmotion_ros_node-1] QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
[ERROR] [witmotion_ros_node-1]: process has died [pid 28526, exit code -11, cmd '/root/home/colcon_ws/install/witmotion_ros/lib/witmotion_ros/witmotion_ros_node --ros-args --params-file /root/home/colcon_ws/install/witmotion_ros/share/witmotion_ros/config/wt901.yml'].

wt901.yml show under the contents.
witmotion:
  ros__parameters:
    port: ttyUSB0
    baud_rate: 115200 # baud
    polling_interval: 50 # ms
    timeout_ms: 150 # ms
    restart_service_name: /restart_imu
    imu_publisher:
      topic_name: /imu
      frame_id: imu
      use_native_orientation: true
      measurements:
        acceleration:
          enabled: true
          covariance: [0.0364, 0.0, 0.0, 0.0, 0.0048, 0.0, 0.0, 0.0, 0.0796]
        angular_velocity:
          enabled: true
          covariance: [0.0663, 0.0, 0.0, 0.0, 0.1453, 0.0, 0.0, 0.0, 0.0378]
        orientation:
          enabled: true
          covariance: [0.0479, 0.0, 0.0, 0.0, 0.0207, 0.0, 0.0, 0.0, 0.0041]
    temperature_publisher:
      enabled: true
      topic_name: /temperature
      frame_id: base_link
      from_message: magnetometer # acceleration, angular_vel, orientation, magnetometer
      variance: 0.01829
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
    magnetometer_publisher:
      enabled: true
      topic_name: /magnetometer
      frame_id: compass
      coefficient: 0.00000001 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
      covariance:
        [0.000000187123, 0.0, 0.0, 0.0, 0.000000105373, 0.0, 0.0, 0.0, 0.000000165816]
    barometer_publisher:
      enabled: false
      topic_name: /barometer
      frame_id: base_link
      variance: 0.001
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
    altimeter_publisher:
      enabled: false
      topic_name: /altitude
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
    orientation_publisher:
      enabled: true
      topic_name: /orientation
    gps_publisher:
      enabled: false
      navsat_fix_frame_id: world
      navsat_fix_topic_name: /gps
      navsat_altitude_topic_name: /gps_altitude
      navsat_satellites_topic_name: /gps_satellites
      navsat_variance_topic_name: /gps_variance
      ground_speed_topic_name: /gps_ground_speed
    rtc_publisher:
      enabled: false
      topic_name: /witmotion_clock
      
How can i solve it? Thank you.

**Comment by twdragon** [comment]
> `use_native_orientation: true`

Your issue probably described here: https://wiki.ros.org/witmotion_ros/Troubleshooting#Absence_of_quaternion_orientation_output
