### ISSUE TITLE
Issue with HWT 905-485 Sensor - Timed Out Waiting for Data

### ISSUE THREAD

**Issue by melhem17** [ElettraSciComp/witmotion_IMU_ros#37]
I am currently in the process of setting it up using the ROS driver provided on your GitHub repository.
I followed the installation instructions meticulously, including the prerequisites, and successfully built the package using the following commands:

cd catkin_ws
git clone --recursive https://github.com/ElettraSciComp/witmotion_IMU_ros.git src/witmotion_ros
catkin_make

Everything seemed to work well until I attempted to launch the sensor using the command:
roslaunch witmotion_ros witmotion.launch
However, I encountered an issue with the attached error message.

![406503414_895426495325657_5975897381191548365_n](https://github.com/ElettraSciComp/witmotion_IMU_ros/assets/138404973/a99832ec-f44f-44c8-9283-a74c54aead35)

I have verified the device connection and baudrate settings, but the issue persists. 
I would greatly appreciate any guidance or troubleshooting steps you can provide to help me overcome this challenge.

**Comment by twdragon** [comment]
@melhem17 can you connect the device using another program?

**Comment by twdragon** [comment]
Closed due to inactivity

**Comment by Albert-wa** [comment]
> [@melhem17](https://github.com/melhem17) can you connect the device using another program?

the same Timed out issue with 905-485, which program should I try to find the problem?
